/**
 * 中文国家名 → ECharts 世界地图 GeoJSON 英文名映射
 *
 * GeoJSON 数据源使用缩写英文名（如 "United States"、"Dem. Rep. Congo"），
 * 而 Nominatim 反向地理编码返回的是中文名（如 "美国"、"刚果民主共和国"）。
 * 此映射用于将中文国家名转换为 GeoJSON 中匹配的名称，使热力图正确着色。
 */

const COUNTRY_ZH_TO_GEOJSON: Record<string, string> = {
  // 亚洲
  中国: 'China',
  日本: 'Japan',
  韩国: 'Korea',
  朝鲜: 'Dem. Rep. Korea',
  印度: 'India',
  泰国: 'Thailand',
  越南: 'Vietnam',
  印度尼西亚: 'Indonesia',
  印尼: 'Indonesia',
  马来西亚: 'Malaysia',
  新加坡: 'Singapore',
  菲律宾: 'Philippines',
  柬埔寨: 'Cambodia',
  老挝: 'Lao PDR',
  缅甸: 'Myanmar',
  文莱: 'Brunei',
  东帝汶: 'Timor-Leste',
  蒙古: 'Mongolia',
  蒙古国: 'Mongolia',
  哈萨克斯坦: 'Kazakhstan',
  乌兹别克斯坦: 'Uzbekistan',
  土库曼斯坦: 'Turkmenistan',
  吉尔吉斯斯坦: 'Kyrgyzstan',
  塔吉克斯坦: 'Tajikistan',
  阿富汗: 'Afghanistan',
  巴基斯坦: 'Pakistan',
  孟加拉国: 'Bangladesh',
  孟加拉: 'Bangladesh',
  斯里兰卡: 'Sri Lanka',
  尼泊尔: 'Nepal',
  不丹: 'Bhutan',
  伊朗: 'Iran',
  伊拉克: 'Iraq',
  叙利亚: 'Syria',
  约旦: 'Jordan',
  黎巴嫩: 'Lebanon',
  以色列: 'Israel',
  巴勒斯坦: 'Palestine',
  沙特阿拉伯: 'Saudi Arabia',
  也门: 'Yemen',
  阿曼: 'Oman',
  阿联酋: 'United Arab Emirates',
  阿拉伯联合酋长国: 'United Arab Emirates',
  卡塔尔: 'Qatar',
  巴林: 'Bahrain',
  科威特: 'Kuwait',
  土耳其: 'Turkey',
  亚美尼亚: 'Armenia',
  阿塞拜疆: 'Azerbaijan',
  格鲁吉亚: 'Georgia',
  塞浦路斯: 'Cyprus',

  // 欧洲
  英国: 'United Kingdom',
  法国: 'France',
  德国: 'Germany',
  意大利: 'Italy',
  西班牙: 'Spain',
  葡萄牙: 'Portugal',
  荷兰: 'Netherlands',
  比利时: 'Belgium',
  卢森堡: 'Luxembourg',
  瑞士: 'Switzerland',
  奥地利: 'Austria',
  波兰: 'Poland',
  捷克: 'Czech Rep.',
  捷克共和国: 'Czech Rep.',
  斯洛伐克: 'Slovakia',
  匈牙利: 'Hungary',
  罗马尼亚: 'Romania',
  保加利亚: 'Bulgaria',
  希腊: 'Greece',
  瑞典: 'Sweden',
  挪威: 'Norway',
  丹麦: 'Denmark',
  芬兰: 'Finland',
  冰岛: 'Iceland',
  爱尔兰: 'Ireland',
  乌克兰: 'Ukraine',
  白俄罗斯: 'Belarus',
  白罗斯: 'Belarus',
  俄罗斯: 'Russia',
  爱沙尼亚: 'Estonia',
  拉脱维亚: 'Latvia',
  立陶宛: 'Lithuania',
  摩尔多瓦: 'Moldova',
  塞尔维亚: 'Serbia',
  克罗地亚: 'Croatia',
  斯洛文尼亚: 'Slovenia',
  波黑: 'Bosnia and Herz.',
  波斯尼亚和黑塞哥维那: 'Bosnia and Herz.',
  北马其顿: 'Macedonia',
  马其顿: 'Macedonia',
  阿尔巴尼亚: 'Albania',
  黑山: 'Montenegro',
  列支敦士登: 'Liechtenstein',
  安道尔: 'Andorra',
  马耳他: 'Malta',

  // 北美洲
  美国: 'United States',
  加拿大: 'Canada',
  墨西哥: 'Mexico',
  危地马拉: 'Guatemala',
  伯利兹: 'Belize',
  萨尔瓦多: 'El Salvador',
  洪都拉斯: 'Honduras',
  尼加拉瓜: 'Nicaragua',
  哥斯达黎加: 'Costa Rica',
  巴拿马: 'Panama',
  古巴: 'Cuba',
  牙买加: 'Jamaica',
  海地: 'Haiti',
  多米尼加: 'Dominican Rep.',
  多米尼加共和国: 'Dominican Rep.',
  巴哈马: 'Bahamas',
  特立尼达和多巴哥: 'Trinidad and Tobago',
  巴巴多斯: 'Barbados',
  格林纳达: 'Grenada',
  圣卢西亚: 'Saint Lucia',
  多米尼克: 'Dominica',

  // 南美洲
  巴西: 'Brazil',
  阿根廷: 'Argentina',
  智利: 'Chile',
  哥伦比亚: 'Colombia',
  秘鲁: 'Peru',
  委内瑞拉: 'Venezuela',
  厄瓜多尔: 'Ecuador',
  玻利维亚: 'Bolivia',
  巴拉圭: 'Paraguay',
  乌拉圭: 'Uruguay',
  圭亚那: 'Guyana',
  苏里南: 'Suriname',

  // 非洲
  埃及: 'Egypt',
  南非: 'South Africa',
  尼日利亚: 'Nigeria',
  肯尼亚: 'Kenya',
  埃塞俄比亚: 'Ethiopia',
  坦桑尼亚: 'Tanzania',
  乌干达: 'Uganda',
  阿尔及利亚: 'Algeria',
  摩洛哥: 'Morocco',
  突尼斯: 'Tunisia',
  利比亚: 'Libya',
  苏丹: 'Sudan',
  南苏丹: 'S. Sudan',
  索马里: 'Somalia',
  吉布提: 'Djibouti',
  厄立特里亚: 'Eritrea',
  加纳: 'Ghana',
  科特迪瓦: "Côte d'Ivoire",
  喀麦隆: 'Cameroon',
  尼日尔: 'Niger',
  布基纳法索: 'Burkina Faso',
  马里: 'Mali',
  塞内加尔: 'Senegal',
  几内亚: 'Guinea',
  塞拉利昂: 'Sierra Leone',
  利比里亚: 'Liberia',
  多哥: 'Togo',
  贝宁: 'Benin',
  马拉维: 'Malawi',
  赞比亚: 'Zambia',
  津巴布韦: 'Zimbabwe',
  莫桑比克: 'Mozambique',
  博茨瓦纳: 'Botswana',
  纳米比亚: 'Namibia',
  莱索托: 'Lesotho',
  斯威士兰: 'Swaziland',
  马达加斯加: 'Madagascar',
  毛里求斯: 'Mauritius',
  塞舌尔: 'Seychelles',
  安哥拉: 'Angola',
  刚果: 'Congo',
  刚果共和国: 'Congo',
  刚果民主共和国: 'Dem. Rep. Congo',
  '刚果(金)': 'Dem. Rep. Congo',
  '刚果(布)': 'Congo',
  加蓬: 'Gabon',
  赤道几内亚: 'Eq. Guinea',
  中非: 'Central African Rep.',
  中非共和国: 'Central African Rep.',

  乍得: 'Chad',
  卢旺达: 'Rwanda',
  布隆迪: 'Burundi',
  毛里塔尼亚: 'Mauritania',
  冈比亚: 'Gambia',
  几内亚比绍: 'Guinea-Bissau',
  佛得角: 'Cape Verde',

  // 大洋洲
  澳大利亚: 'Australia',
  新西兰: 'New Zealand',
  巴布亚新几内亚: 'Papua New Guinea',
  斐济: 'Fiji',
  所罗门群岛: 'Solomon Is.',
  瓦努阿图: 'Vanuatu',
  萨摩亚: 'Samoa',
  基里巴斯: 'Kiribati',
  汤加: 'Tonga',
  帕劳: 'Palau',
};

/**
 * 将国家名称转换为 ECharts 世界地图 GeoJSON 中使用的名称
 *
 * 优先查找中文映射，若未命中则原样返回（兼容已经是英文名的情况）。
 */
export function toGeoJsonCountryName(name: string): string {
  return COUNTRY_ZH_TO_GEOJSON[name] ?? name;
}
