/**
 * 类型定义统一导出文件
 */

// 导出数据库类型
export type {
  Database,
  User,
  City,
  WishlistItem,
  Trip,
  TripDay,
  TripTask,
  Share,
  Tables,
  CityInsert,
  CityUpdate,
  WishlistItemInsert,
  WishlistItemUpdate,
  TripInsert,
  TripUpdate,
  TripDayInsert,
  TripDayUpdate,
  TripTaskInsert,
  TripTaskUpdate,
  ShareInsert,
  TableRow,
  TableInsert,
  TableUpdate,
} from './database';

// 导出业务实体类型
export {
  TripType,
  TripStatus,
  ShareType,
  Continent,
  Season,
} from './entities';

export type {
  CityFormData,
  WishlistFormData,
  TripFormData,
  TripDayFormData,
  TripTaskFormData,
  ProfileFormData,
  LoginFormData,
  RegisterFormData,
  CityWithTrips,
  TripWithDetails,
  UserWithStats,
  Coordinates,
  MapMarker,
  MapViewState,
  GeocodingResult,
  TravelStatistics,
  CountryStatistics,
  ContinentStatistics,
  YearlyStatistics,
  ChartData,
  ShareData,
  CreateShareRequest,
  ShareResponse,
  CitySearchParams,
  TripFilterParams,
  SearchResult,
  DraftData,
  SyncStatus,
  ApiResponse,
  ApiError,
  PaginatedResponse,
  SidebarState,
  ModalState,
  LoadingState,
  Notification,
  Timestamps,
  UserOwned,
} from './entities';
